import os
import sys
from dotenv import load_dotenv

# Load env
load_dotenv()

print("--- Starting Diagnostic (Gemini Mode) ---")

# Check API Key
api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    # also check if hidden or something
    print("ERROR: GEMINI_API_KEY is missing from environment.")
else:
    print(f"Gemini API Key found: {api_key[:5]}...{api_key[-4:]}")

# Test 1: Script Writer (Gemini)
print("\n--- Testing Script Writer (Gemini) ---")
try:
    from pipeline.script_writer import write_script
    script = write_script("Interesting Space Facts")
    if script:
        print("Success: Script generated by Gemini.")
        for i, line in enumerate(script):
            print(f"Line {i+1}: {line}")
    else:
        print("FAILURE: Script writer returned empty list.")
except Exception as e:
    print(f"EXCEPTION in Script Writer: {e}")

# Test 2: Image Generator (Mock)
print("\n--- Testing Image Generator (Mock) ---")
try:
    from pipeline.image_generator import generate_images
    # Use a dummy script
    dummy_script = ["Scene 1: Space is vast.", "Scene 2: Stars are bright."]
    images = generate_images(dummy_script)
    if images:
        print(f"Success: {len(images)} mock images generated.")
        print(images)
    else:
        print("FAILURE: Image generator returned empty list.")
except Exception as e:
    print(f"EXCEPTION in Image Generator: {e}")

print("\n--- Diagnostic Complete ---")
